### ISSUE TITLE
When group-by-instances is set to true the instances created by @Factory does not run in parallel

### ISSUE THREAD

**Issue by christoe** [testng-team/testng#326] opened 2013-01-15 12:51 UTC
Running this on TestNG 6.8:

```java
package test;

import org.apache.log4j.Logger;
import org.testng.annotations.*;
import org.testng.annotations.Test;

public class TestTest
{
    private String param;

    @Factory( dataProvider = "prov" )
    public TestTest( String param )
    {
        this.param = param;
    }

    @DataProvider( name = "prov" )
    public static Object[][] dataProvider()
    {
        System.out.println( "[" + Thread.currentThread().getId() +  "] Provide data" );
        return new Object[][] {
                { "One" },
                { "Two" },
                { "Three" },
        };
    }

    @BeforeClass
    public void prepare()
    {
        System.out.println( "[" + Thread.currentThread().getId() +  "] Prepare " + param );
    }

    @Test
    public void test1()
    {
        System.out.println( "[" + Thread.currentThread().getId() +  "] Test1 " + param );
    }

    @Test( dependsOnMethods = "test1" )
    public void test2()
    {
        System.out.println( "[" + Thread.currentThread().getId() +  "] Test2 " + param );
        sleep();
    }

    @AfterClass
    public void clean()
    {
        System.out.println( "[" + Thread.currentThread().getId() +  "] Clean " + param );
    }

    private void sleep() {
        try {
            Thread.sleep(10000);
        } catch (Exception ignored) {}
    }
}
```

With the following testng.xml:

```xml
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >

<suite name="Suite" parallel="instances" thread-count="5" group-by-instances="true">
  <test name="Tests">
    <classes>
       <class name="test.TestTest" />
    </classes>
  </test>
</suite>
```

Results in:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running TestSuite
[1] Provide data
[9] Prepare Three
[9] Test1 Three
[10] Test2 Three
[10] Clean Three
[11] Prepare Two
[11] Test1 Two
[12] Test2 Two
[12] Clean Two
[13] Prepare One
[13] Test1 One
[13] Test2 One
[13] Clean One
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.61 sec
```

With `Thread.sleep()`, I'm expecting the other threads to kick in and that the runtime should be just over 10 seconds. This is true when group-by-instances is set to false, but I need my test cases to run together for my WebDriver tests not to time out.

I'm also slightly confused over the thread-id's. From the documentation: `parallel="instances"`: TestNG will run all the methods in the same instance in the same thread, but two methods on two different instances will be running in different threads. The output above seems to indicate that this is not the case, but methods from the same instance is running on two different threads, even if they are executed in the right order.

**Comment by bherrington0421** [comment] 2015-04-15 21:51
Sorry to resurrect an old issue. But is there any conclusion on this? Is this the expected behavior of group-by-instances="true"?

**Comment by gulwaniv** [comment] 2015-06-08 06:13
I am also facing similar issue, can someone please help me on this

**Comment by krmahadevan** [comment] 2015-06-10 02:37
Can you please help elaborate as to what your issue is ?
I believe I did share some tweaks to the configuration which seemed to
start triggering the instances to be run in parallel from a Factory.
It would be good if you could please add more context.

Thanks & Regards
Krishnan Mahadevan

"All the desirable things in life are either illegal, expensive, fattening
or in love with someone else!"
My Scribblings @ http://wakened-cognition.blogspot.com/
My Technical Scribbings @ http://rationaleemotions.wordpress.com/

**Comment by gulwaniv** [comment] 2015-06-10 12:37
I want to run instances in parallel with each test case should be group by instances. When I am running the code, I am facing the instances are not running in parallel but the test case group by instances is working as expected. 

I added parallel=true in factory data provider and also I added attribute parallel="classes" in .xml file but it didn't helped me.

**Comment by adamjson** [comment] 2016-04-20 16:29
This is still a huge problem for us. We have Factory tests that need to run in parallel, and we want all of the test methods for an instance to execute in order, and not block until all the same methods have been executed in all other instances. Essentially what happens is that our selenium tests should be finishing gracefully and opening slots on the grid for other tests to run, but instead with group-by-instances="false" they sit idle until all instances have finished testing, and then they all attempt to execute the next test method at once, but at that time the browser has been sitting idle too long and has timed out.

Setting group-by-instances="true" ensures that the test methods run sequentially and do not block until the other instances have finished, **however they stop running in parallel**. So the solution to the problem, creates yet another problem which I've been unable to solve. Am I missing a workaround for this?

**Comment by mfulton26** [comment] 2016-06-17 13:55
I'm also running into this issue. What is needed in order to find and implement a fix for this? Is a concrete example still needed or is the issue understood well enough already? I could take a moment and provide a full example if it would help.

**Comment by juherr** [comment] 2016-06-17 14:26
Minimal and runnable example always helps ;)

**Comment by mfulton26** [comment] 2016-06-17 14:37
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Demonstration Suite" parallel="instances">
    <test name="Test Issue #326 · cbeust/testng">
        <classes>
            <class name="CountDownLatchTest"/>
        </classes>
    </test>
</suite>
```

```java
public class CountDownLatchTest {
    private static final CountDownLatch COUNT_DOWN_LATCH = new CountDownLatch(10);

    @Factory
    public static Object[] createSomeTestInstances() {
        return Stream.generate(CountDownLatchTest::new).limit(10).toArray();
    }

    @BeforeClass
    public void setUpClass() throws InterruptedException {
        COUNT_DOWN_LATCH.countDown();
        COUNT_DOWN_LATCH.await();
    }

    @Test
    public void something() {
        // never gets here; only one instance of this class gets `setUpClass` invoked but all 10
        // should get invoked relatively quickly
    }
}
```

**Comment by mfulton26** [comment] 2016-08-05 16:35
@juherr Does the minimal/runnable example I provided help? Can this issue get prioritized? Thanks!

**Comment by juherr** [comment] 2016-08-05 16:53
I didn't check yet because I don't have enough free time. But I can help you to propose a fix if you want to try.

**Comment by mfulton26** [comment] 2016-08-05 18:40
Sure. I'll pull down the sources and figure out how to build them, etc.

**Comment by juherr** [comment] 2016-08-05 19:14
:+1:

**Comment by zeeshanny** [comment] 2016-08-15 14:33
We are also having the same issue. Could you please help us with this issue. I would really appreciate it. Thanks

**Comment by c0gupr2** [comment] 2016-08-15 16:10
@mfulton26 
Hi, 

I am also facing same issue. 
Could you please help me with a solution incase you found one?

Thanks,
Rohit Gupta

**Comment by da-sergey-obruch** [comment] 2016-08-17 14:33
@mfulton26 
Hi! If you have any ideas how to handle it, could you please help me too with it? I would very appreciate it. 
Thanks

**Comment by mfulton26** [comment] 2016-08-17 18:03
I have not yet had a chance to look into this. As far as I got was downloading and building from the sources.

**Comment by BrandonDude** [comment] 2017-01-27 18:56
Just trying to keep this alive...
It would be nice to run multiple threads and have each one be "grouped by instance".

**Comment by juherr** [comment] 2017-01-27 19:15
@BrandonDude Do you confirm the issue still exist with 6.10 and 6.11-SNAPSHOT?

**Comment by BrandonDude** [comment] 2017-06-12 17:13
Yes, this is still an issue in **6.11** when using _parallel="instances"_, _group-by-instances="true"_, and _@Test( dependsOnMethods = { "" } )_

**Comment by BrandonDudek** [comment] 2018-07-10 14:47
Just trying to get this some attention...

It is still a bug in **v6.14.3**.

I created a sample project to showcase/test the bug: https://github.com/BrandonDudek/testng-bug-parallel-group-by-instances

**Comment by mmarciniuk** [comment] 2019-01-20 20:35
I'm also facing this problem (version 6.14.3).

I used version 7.0.0-beta3 and it looks that in this version this issue no longer exists. I hope version 7 will have a final release soon.

**Comment by ilusi0npl** [comment] 2019-03-14 11:47
I've tried code from https://github.com/BrandonDudek/testng-bug-parallel-group-by-instances with 7.0.0-beta3 and it works the same. Bug still there. When you plan to fix it?

**Comment by krmahadevan** [comment] 2019-03-15 04:28
@ilusi0npl - The issue still is open. So the problem will be there even in the latest released version.

> When you plan to fix it?

At the earliest is what I can tell you. There are not many contributors for TestNG who are willing to help us out. So if you are willing to help fix this issue, we are more than happy to help you with review and merge. If not, please be patient. We are doing the best we can

**Comment by krmahadevan** [comment] 2019-03-18 09:15
@juherr / @cbeust  - Here's my analysis on this issue.

Basically there are two combinations when working with `instances` as my parallelism strategy.

1. `group-by-instances` as `true`
2. `group-by-instances` as `false`

**Current behavior** 
By default, when TestNG sees the parallelism strategy as `instances`, it uses `org.testng.internal.InstanceBasedParallelParallelWorker` to support this behavior.

When TestNG sees `group-by-instances` as `true`, it internally establishes dependencies amongst instances such that methods that belong to a particular instance along can run at a given point in time.

**Proposed behavior** 
Here's the proposed changes that I am suggesting.

* `parallel="instances"` and `group-by-instances=false` - Should not be treated as a special case. Here the user is merely asking TestNG that it resort to parallel instances execution.  The only difference between `parallel=methods` and `parallel=instances` is that in the case of `methods`, TestNG determines how to create the instances and in the case of `instances` the user instructs TestNG how to create instances. So we need to change this behavior such that TestNG behaves the same way in terms of parallel execution of methods, when they choose either `methods` (or) `instances`

* `parallel="instances"` and `group-by-instances=true` - In this case, TestNG should do the following. 

1. We should remove this codebase 

https://github.com/cbeust/testng/blob/c03a52eed028e1a3d43398c1fc63110662294f1a/src/main/java/org/testng/internal/DynamicGraphHelper.java#L91-L99

 2. We should use `org.testng.internal.InstanceBasedParallelParallelWorker` only for this combination.

This change is already causing 32 test cases to fail (locally). So I want to check if this is acceptable before I proceed further with getting this done.

**Comment by juherr** [comment] 2019-03-18 10:47
@krmahadevan 
Could we manage it by steps?
1. Start by a PR with only your `parallel="instances" and group-by-instances=true` proposition? Can you list the failing tests there?
2. When done, same for your first proposition

**Comment by krmahadevan** [comment] 2019-03-18 11:38
The list of failing tests are as below

```
DynamicGraphHelperTest. testCreateDynamicGraphWithGroupByInstances
DynamicGraphHelperTest. testCreateDynamicGraphWithGroupByInstances
DynamicGraphHelperTest. testCreateDynamicGraphWithGroupByInstances
DynamicGraphHelperTest. testCreateDynamicGraphWithGroupByInstances
DependentTest. dependentWithDataProvider
DependentTest. dependentWithDataProvider
DependentTest. dependentWithDataProvider
DependentTest. dependentWithDataProvider
GroupByInstancesTest. groupByInstances
GroupByInstancesTest. groupByInstances
GroupByInstancesTest. groupByInstances
GroupByInstancesTest. groupByInstances
GroupBugTest. shouldOrderByClass
GroupBugTest. shouldOrderByClass
GroupBugTest. shouldOrderByClass
GroupBugTest. shouldOrderByClass
ParallelTestTest. verifyParallelWithFactory[2](true, instances, 2)
ParallelTestTest. verifyParallelWithFactory[2](true, instances, 2)
ParallelTestTest. verifyParallelWithFactory[2](true, instances, 2)
ParallelTestTest. verifyParallelWithFactory[2](true, instances, 2)
ParallelTestTest. verifyParallelWithFactory[3](false, instances, 2)
ParallelTestTest. verifyParallelWithFactory[3](false, instances, 2)
ParallelTestTest. verifyParallelWithFactory[3](false, instances, 2)
ParallelTestTest. verifyParallelWithFactory[3](false, instances, 2)
ParallelTestTest. verifyParallel[8](true, instances, 2)
ParallelTestTest. verifyParallel[8](true, instances, 2)
ParallelTestTest. verifyParallel[8](true, instances, 2)
ParallelTestTest. verifyParallel[8](true, instances, 2)
ParallelTestTest. verifyParallel[9](false, instances, 2)
ParallelTestTest. verifyParallel[9](false, instances, 2)
ParallelTestTest. verifyParallel[9](false, instances, 2)
ParallelTestTest. verifyParallel[9](false, instances, 2)
```

**Comment by juherr** [comment] 2019-03-18 13:14
@krmahadevan It is a lot of changes :( Is it the result with both changes or only the second one?

**Comment by krmahadevan** [comment] 2019-03-18 13:16
Its with both. Like I said, its going to change how TestNG looks at both those two combinations.

I feel that perhaps TestNG was handling it incorrectly when it came to `parallel="instances"` + `group-by-instances=false`.

That was why I wanted to know if I can go ahead and fix this.

**Comment by juherr** [comment] 2019-03-18 14:15
Just try with the `parallel="instances" and group-by-instances=true` suggestion in a first step/pr.

**Comment by krmahadevan** [comment] 2019-03-19 17:27
@juherr - I managed to fix this issue without a lot of regression. Please take a look at the PR.

**Closed** 2019-03-20 09:11 UTC
Labels: area: parallel execution, area: execution order, area: factory, area: data provider

**Comment by BrandonDudek** [comment] 2019-04-08 18:32
@krmahadevan & @juherr, Thanks! Can't wait to test out a release. :)

**Comment by BrandonDudek** [comment] 2019-04-09 00:42
Just ran it against 7.0.0-beta5, and it worked!
Thanks again!!!

**Comment by holbrod** [comment] 2019-04-29 11:22
Do you have an ETA when 7.0.0-beta5 will be available? or when 7 will be released?

**Comment by juherr** [comment] 2019-04-29 11:51
Will be 7.0.0-beta5.

@cbeust Feel free to run a beta release when you'll have the time.
