### ISSUE TITLE
Injection errors with test classes annotated at class level that implement interfaces with default methods even when those use @NoInjection

### ISSUE THREAD

**Issue by javydreamercsw** [testng-team/testng#2983] opened 2023-09-21 13:59 UTC
### TestNG Version
7.8.0

### Expected behavior
@NoInjection is respected regardless of where it includes inheritance or interface default implementations.

### Actual behavior
Methods using @NoInjection, if they are inherited via an interface with default methods, give injection errors.

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [X] NetBeans

### Test case sample
See attachment. [Example.zip](https://github.com/testng-team/testng/files/12685463/Example.zip)

**Comment by krmahadevan** [comment] 2023-09-22 05:04
@javydreamercsw - I dont see any references of `@NoInjection` annotation being used in conjunction with a **Non data driven test** method. It was always meant to be used with a data driven test method.

So I dont think this ever worked. I do see what may have caused the confusion because the javadocs of this annotation doesn't make it explicitly clear.

The user facing documentation [native-dependency-injection](https://testng.org/doc/documentation-main.html#native-dependency-injection) adds a bit more context around this.

Also by design TestNG would like to deal with a parameterised method ONLY on the following conditions

* It's parameters are not any of the native injection data types listed in the above documentation link
* The method is annotated with `@Parameters` annotation hinting at the method parameters being derived from a suite file
* The method is attributed with a `dataprovider` attribute

**Comment by javydreamercsw** [comment] 2023-09-22 10:40
Then I guess is trying to do way more than that.

**Comment by krmahadevan** [comment] 2023-09-22 11:17
Not sure i understand what you mean. Can you please clarify?

**Comment by javydreamercsw** [comment] 2023-09-23 00:11
From what you said it seems this should be ignored by TestNG and not being
a problem since is not any of the scenarios you described.

**Comment by krmahadevan** [comment] 2023-09-23 01:59
This method is being considered by TestNG because there is a `@Test` annotation added at the class level. This causes TestNG to treat all public methods in the class as test method. 

If you remove that class level annotation and annotate individual methods then you shouldnt see this behaviour. 

Can you please try @javydreamercsw

**Comment by juherr** [comment] 2023-09-23 13:46
Or maybe just add `@Ignore` on the method you don't want.
Not sure if it will work.

**Comment by javydreamercsw** [comment] 2023-09-23 14:16
I'll try that, but the no injection should work in theory and it just
doesn't for this case.

**Comment by javydreamercsw** [comment] 2023-09-23 14:16
Is this a TestNG annotation?

**Comment by krmahadevan** [comment] 2023-09-23 14:19
@javydreamercsw 

> but the no injection should work in theory and it just doesn't for this case.

Yes. I hear you. @juherr WDYT ? 

> Is this a TestNG annotation?

Yes. That is a TestNG annotation.

**Comment by krmahadevan** [comment] 2023-09-24 02:40
@javydreamercsw 

> but the no injection should work in theory and it just doesn't for this case.

I thought through this a bit more. 

Let's say that testng honours the `@NoInjection` annotation on the interface's default methods (Which are now getting considered as valid tests because the class that implements the interface is annotated with `@Test` at class level owing to which all methods of the class including the interface provided default methods get considered as tests), the values to the method parameters would not be sent when it gets invoked by TestNG. So if the parameters were primitives they would default to their default values and if the parameters were custom objects or the wrapper types, then they would be getting a `null` value.

In either case, the test method now is going to be failing or displaying unexpected behavior.
So what is the point of having this default method double up as a test method to begin with?

**Comment by juherr** [comment] 2023-09-24 11:26
It sounds like a corner case because over engineering.
I'm not sure it should be supported out of the box.

**Comment by javydreamercsw** [comment] 2023-09-24 21:45
The interface is not annotated with @Test but have default methods defined.
The class that implements the interface has @Test at class level and tries
to run the default methods from the interface as tests.

**Comment by juherr** [comment] 2023-09-25 07:14
> Is this a TestNG annotation?

Yes it is https://javadoc.io/doc/org.testng/testng/latest/org/testng/annotations/Ignore.html

**Comment by krmahadevan** [comment] 2023-09-25 11:09
@javydreamercsw 

> The interface is not annotated with @test but have default methods defined. The class that implements the interface has @test at class level and tries to run the default methods from the interface as tests.

Your test class that implements the interface which is having a parameterised default method, has a `@Test` annotation at the class level. This causes TestNG to consider all the public methods in the class to be test methods (that is why the default method is getting visible to TestNG)

You can either add the annotation that @juherr mentioned or remove the class level annotation and explicitly annotate only those methods which are actually tests using the `@Test` annotation.

Am closing this issue

**Comment by javydreamercsw** [comment] 2023-09-25 21:17
That's the issue. Adding the annotation doesn't work as it should and needing to remove the annotation at class level seems unnecessary. We use it for common things like a class-level group. Now multiple tests would need to be updated.

**Comment by javydreamercsw** [comment] 2023-09-25 21:37
Ignore annotation doesn't work either.

**Comment by krmahadevan** [comment] 2023-09-26 07:08
@javydreamercsw - Yes. This was a tricky one. 

Here's how you can go about solving this at your side without needing any changes in TestNG.

1. Add `@org.testng.annotations.Ignore` annotation on your interface's default methods so that they can be marked for being ignored. You can also have this replaced with your own custom annotation that makes it even more obvious.
2. Build a method interceptor that looks like below.
3. Add this method interceptor as a mandatory listener via service loaders as explained in the documentation [here](https://testng.org/doc/documentation-main.html#listeners-service-loader) 

```java
import org.testng.IMethodInstance;
import org.testng.IMethodInterceptor;
import org.testng.ITestContext;
import org.testng.annotations.Ignore;

import java.util.List;
import java.util.stream.Collectors;

public class SimpleTransformer implements IMethodInterceptor {

    @Override
    public List<IMethodInstance> intercept(List<IMethodInstance> methods, ITestContext context) {
        return methods.stream()
                .filter(it -> !it.getMethod().getConstructorOrMethod().getMethod().isAnnotationPresent(Ignore.class))
                .collect(Collectors.toList());
    }
}
```

The reason why just adding `@Ignore` didn't work earlier was because of the way in which the annotation transformation works in TestNG.

* You have the `@Test` at the class level. So individual implemented methods (i.e., methods that belong to the interface) get skipped from inspection. This is because when annotations are being processed in TestNG, TestNG is purely looking at classes and not at objects.
* Since the processing of `@Ignore` annotation is internally done by an annotation transformer, the annotation transformer also doesn't get invoked.

**Closed by krmahadevan** 2023-09-26 07:08 UTC
