### ISSUE TITLE
Unable to run testcases with testng 7.0.0-beta1 in eclipse / maven test

### ISSUE THREAD

**Issue by qatestng** [testng-team/testng#1924] opened 2018-09-27 03:05 UTC
I am using latest testng 7.0.0-beta1 version to show factory parameters in custom report. Below is the dependency in pom.xml

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.0.0-beta1</version>
			<scope>test</scope>
		</dependency>

Eclipse plugin details 

- TestNG	7.0.0.201809110942	org.testng.eclipse.feature.group	Cedric Beust
-   TestNG M2E (Maven) Integration (Optional)	7.0.0.201809110942	org.testng.eclipse.maven.feature.feature.group	TestNG Team
-   TestNG P2 Feature	7.0.0.b201809110940	org.testng.p2.feature.feature.group	TestNG Team

Test case execution is failing in both eclipse and command line. 
In eclipse when running from a testng xml I am getting this exception:

[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "7.0.0-": non-numeric "0-"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] now trying to parse the version from MANIFEST.MF
Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.0.0) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:121)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:49)

When I am running using mvn test from command line I am getting the below exception:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project PaymentPageUITests: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] org.testng.TestNGException: 
[ERROR] 
[ERROR] An error occurred while instantiating class com.nttdhktest.DummyTests. Check to make sure it can be instantiated
[ERROR] 	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:388)
[ERROR] 	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
[ERROR] 	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:110)
[ERROR] 	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:188)
[ERROR] 	at org.testng.TestClass.getInstances(TestClass.java:94)
[ERROR] 	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:79)
[ERROR] 	at org.testng.TestClass.init(TestClass.java:71)
[ERROR] 	at org.testng.TestClass.<init>(TestClass.java:36)
[ERROR] 	at org.testng.TestRunner.initMethods(TestRunner.java:461)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:340)
[ERROR] 	at org.testng.TestRunner.init(TestRunner.java:293)
[ERROR] 	at org.testng.TestRunner.<init>(TestRunner.java:178)
[ERROR] 	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:603)
[ERROR] 	at org.testng.SuiteRunner.init(SuiteRunner.java:194)
[ERROR] 	at org.testng.SuiteRunner.<init>(SuiteRunner.java:125)
[ERROR] 	at org.testng.TestNG.createSuiteRunner(TestNG.java:1230)
[ERROR] 	at org.testng.TestNG.createSuiteRunners(TestNG.java:1209)
[ERROR] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1058)
[ERROR] 	at org.testng.TestNG.runSuites(TestNG.java:997)
[ERROR] 	at org.testng.TestNG.run(TestNG.java:965)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
[ERROR] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] 

Please help!

**Comment by missedone** [comment] 2018-09-27 11:47
@qatestng , fixed in TestNG Eclipse Plugin: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201809271139/

**Comment by missedone** [comment] 2018-09-28 09:01
@qatestng , is it working with simple testng case?

**Comment by qatestng** [comment] 2018-10-05 10:03
I do not face this issue when using only data provider. The below code works perfectly

	@Test (dataProvider = "testData", dataProviderClass = TestDataGeneration.class)
	public void dummyTest2_3(Map map) {
		System.out.println("Testing dummyTest2_3");
		assertTrue(true);
	}
	
	@Test (dataProvider = "testData", dataProviderClass = TestDataGeneration.class)
	public void dummyTest2_4(Map map) {
		System.out.println("Testing dummyTest2_4");
		assertTrue(true);
	}


I am getting the exception when I add factory

private Map testMap;

	public DummyTests2(Map testdataMap) {
		this.testMap = testdataMap;
	}

	@Factory(dataProvider = "testData", dataProviderClass = TestDataGeneration.class)
	public static Object[] createInstances(Map testMap) {
		return new Object[] { new DummyTests2(testMap) };
	}

	@Test 
	public void dummyTest2_3(Map map) {
		System.out.println("Testing dummyTest2_3");
		assertTrue(true);
	}
	
	@Test 
	public void dummyTest2_4(Map map) {
		System.out.println("Testing dummyTest2_4");
		assertTrue(true);
	}


Exception thrown - 

org.testng.TestNGException: 
An error occurred while instantiating class com.nttdhktest.DummyTests2. Check to make sure it can be instantiated
	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:388)
	at org.testng.internal.ClassHelper.createInstance(ClassHelper.java:336)
	at org.testng.internal.ClassImpl.getDefaultInstance(ClassImpl.java:110)
	at org.testng.internal.ClassImpl.getInstances(ClassImpl.java:188)
	at org.testng.TestClass.getInstances(TestClass.java:94)
	at org.testng.TestClass.initTestClassesAndInstances(TestClass.java:79)
	at org.testng.TestClass.init(TestClass.java:71)
	at org.testng.TestClass.<init>(TestClass.java:36)
	at org.testng.TestRunner.initMethods(TestRunner.java:461)
	at org.testng.TestRunner.init(TestRunner.java:340)
	at org.testng.TestRunner.init(TestRunner.java:293)
	at org.testng.TestRunner.<init>(TestRunner.java:223)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:664)
	at org.testng.SuiteRunner.init(SuiteRunner.java:194)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:125)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1230)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1209)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1058)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


The same code works for version 6.14.2. Please advise.

**Comment by missedone** [comment] 2018-10-05 10:46
@juherr sounds like a regression? Pls take a look

**Comment by juherr** [comment] 2018-10-05 13:00
@missedone Do you reproduce the issue?

**Comment by missedone** [comment] 2018-10-05 13:30
@qatestng, could you share a complete sample for reproducing this issue, this will help us diagnosing.

**Comment by qatestng** [comment] 2018-10-08 01:44
I am using the below dependencies in pom.xml

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.0.0-beta1</version>
			<scope>test</scope>
		</dependency>

Test Generation class - 

public class TestDataGeneration {
	@DataProvider(name = "TestData")

	public static Object[][] dataGenerator() throws IOException {
		File file = new File(Constants.testInputXlsxFile);
		FileInputStream fis = new FileInputStream(file);

		XSSFWorkbook wb = new XSSFWorkbook(fis);
		XSSFSheet sheet = wb.getSheetAt(0);
		wb.close();
		int lastRowNum = sheet.getLastRowNum();
		int lastCellNum = sheet.getRow(0).getLastCellNum();
		Object[][] obj = new Object[lastRowNum][1];

		for (int i = 0; i < lastRowNum; i++) {
			Map<Object, Object> datamap = new HashMap<Object, Object>();
			for (int j = 0; j < lastCellNum; j++) {
				datamap.put(sheet.getRow(0).getCell(j).toString(), sheet.getRow(i + 1).getCell(j).toString());
			}
			obj[i][0] = datamap;

		}
		System.out.println("dataGenerator completed");
		return obj;
	}

}


Test Class -

public class DummyTests2 extends Driver {

	private Map testMap;

	public DummyTests2(Map testdataMap) {
		this.testMap = testdataMap;
	}

	@Factory(dataProvider = "TestData", dataProviderClass = TestDataGeneration.class)
	public static Object[] createInstances(Map testMap) {
		return new Object[] { new DummyTests2(testMap) };
	}

	@Test 
	public void dummyTest2_3(Map map) {
		System.out.println("Testing dummyTest2_3");
		assertTrue(true);
	}
	
	@Test 
	public void dummyTest2_4(Map map) {
		System.out.println("Testing dummyTest2_4");
		assertTrue(true);
	}

	@AfterClass
	public void afterClassDumyTest() {

		System.out.println("afterClassDumyTest :: trying to close borwser.....");
		
	}
}


testng xml -

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="SmokeTestsSuite">
	<listeners>


		<listener class-name="com.test.Listeners" />
		<listener class-name="com.test.resources.ExtentReporterNG" />
		<listener class-name="com.test.reporting.CustomReport" /> 

	</listeners>
	<test thread-count="5" name="SmokeTests" group-by-instances="true"
		preserve-order="true">
		<classes>
			<class name="com.nttdhktest.DummyTests2">
				<methods>

					<include name="dummyTest2_4" />
					<include name="dummyTest2_3" />
				</methods>
			</class>

		</classes>
	</test> 
</suite>

**Comment by qatestng** [comment] 2018-10-09 02:34
This issue can be reproduced in this sample project 

[testng.zip](https://github.com/cbeust/testng/files/2458656/testng.zip)

**Comment by juherr** [comment] 2018-10-11 19:03
The issue comes from the factory method because we fixed something around it and it highlight another issue now.

Here, TestNG is seeing a test class and a factory but it is not able to determine that the factory is building the test class. So, it is trying to create it by itself which can't work.

A possible workaround is separating the test logic from the build logic.

Otherwise, we may skip the test class and only run the factory method but we can't be sure it is an expected behavior (the factory method may create some other test classes).

@krmahadevan @cbeust WDYT?

**Comment by krmahadevan** [comment] 2018-10-12 02:45
@juherr - Yes you are correct. I also came to the same conclusion in terms of the cause of the problem. For some reason TestNG is trying to explicitly instantiate a class using the default constructor, even though the class has a `@Factory` annotated method. Let me see if I can fix this and raise a PR.

**Comment by juherr** [comment] 2018-10-12 04:31
@krmahadevan it is the expected behavior. 
An option could be to run the factory an check if a generated instance is an instance of the current class.

**Comment by qatestng** [comment] 2018-10-18 04:04
Hi All, is there a work around ? I am trying to print the factory parameters in report. Is it possible to achieve that in 6.14 ?

**Closed** 2018-11-11 15:16 UTC
Labels: area: factory, aspect: regression, type: bug

**Comment by sen1983** [comment] 2018-11-27 06:42
When trying to implement ITestListener, in eclipse its not showing the quick fix option Add Unimplemented methods. Please check the other interfaces too I have faced this issue with other interfaces too.

**Comment by NAGENDR189** [comment] 2020-05-01 10:33
Cannot complete the request.  See the error log for details.
"TestNG M2E (Maven) Integration (Optional)" will be ignored because a newer version is already installed. 
"TestNG P2 Feature" will be ignored because a newer version is already installed. 
"TestNG" will be ignored because a newer version is already installed. 


I am unable to install TestNG in my eclipse. Could anyone help me on this??

**Comment by anjaneeucsc** [comment] 2021-05-13 08:27
@NAGENDR189 
Goto Eclipse marketplace and removed the TestNG plugin.
Then try to install the TestNG version you want.
Worked for me. Good luck!
