### ISSUE TITLE
TestNG test suites are executed multiple times when run with maven test

### ISSUE THREAD

**Issue by gcosmiano** [testng-team/testng#508] opened 2014-04-08 12:50 UTC
TestNG test suite are executed multiple times if run in Maven test. Here is what I have in pom.xml

``` xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.8.1</version>
                <configuration>
                    <forkMode>pertest</forkMode>
                    <encoding>UTF-8</encoding>
                    <inputEncoding>UTF-8</inputEncoding>
                    <outputEncoding>UTF-8</outputEncoding>
                    <argLine>-Xms256m -Xmx1024m -ea -Dfile.encoding=UTF-8</argLine> <!-- -ea: assertions enabled   file.encoding: setting the platform default character set -->
                    <suiteXmlFiles>
                        <suiteXmlFile>testngA.xml</suiteXmlFile>
                        <suiteXmlFile>testngB.xml</suiteXmlFile>
                        <suiteXmlFile>testngC.xml</suiteXmlFile>
                        <suiteXmlFile>testngD.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
```

Here is the result and you can see that the test suite were executed multiple times

[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building TestNGParallelTest 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ TestNGParallelTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\U0020941\Documents\Projects\Miscellaneous\TestNGParallelTest\src\main\resources\beans
[INFO] skip non existing resourceDirectory C:\Users\U0020941\Documents\Projects\Miscellaneous\TestNGParallelTest\src\main\config
[INFO] skip non existing resourceDirectory C:\Users\U0020941\Documents\Projects\Miscellaneous\TestNGParallelTest\src\main\resources\schema
[INFO] skip non existing resourceDirectory C:\Users\U0020941\Documents\Projects\Miscellaneous\TestNGParallelTest\data
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ TestNGParallelTest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ TestNGParallelTest ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ TestNGParallelTest ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.8.1:test (default-test) @ TestNGParallelTest ---
[INFO] Surefire report directory: C:\Users\U0020941\Documents\Projects\Miscellaneous\TestNGParallelTest\target\surefire-reports

---
##  T E S T S

Running TestSuite
2014-04-08 08:33:20.782 Thread-16   TestA.class --- 7
2014-04-08 08:33:20.783 Thread-18   TestA.class --- 9
2014-04-08 08:33:20.782 Thread-11   TestA.class --- 2
2014-04-08 08:33:20.782 Thread-14   TestA.class --- 5
2014-04-08 08:33:20.783 Thread-9    TestA.class --- 0
2014-04-08 08:33:20.783 Thread-10   TestA.class --- 1
2014-04-08 08:33:20.783 Thread-12   TestA.class --- 3
2014-04-08 08:33:20.782 Thread-13   TestA.class --- 4
2014-04-08 08:33:20.782 Thread-15   TestA.class --- 6
2014-04-08 08:33:20.783 Thread-17   TestA.class --- 8
2014-04-08 08:33:20.854 Thread-21   TestB.class --- 2
2014-04-08 08:33:20.854 Thread-22   TestB.class --- 3
2014-04-08 08:33:20.854 Thread-20   TestB.class --- 1
2014-04-08 08:33:20.855 Thread-23   TestB.class --- 4
2014-04-08 08:33:20.854 Thread-19   TestB.class --- 0
2014-04-08 08:33:20.855 Thread-25   TestB.class --- 6
2014-04-08 08:33:20.855 Thread-27   TestB.class --- 8
2014-04-08 08:33:20.855 Thread-24   TestB.class --- 5
2014-04-08 08:33:20.855 Thread-28   TestB.class --- 9
2014-04-08 08:33:20.855 Thread-26   TestB.class --- 7
2014-04-08 08:33:20.868 Thread-30   TestC.class --- 1
2014-04-08 08:33:20.868 Thread-29   TestC.class --- 0
2014-04-08 08:33:20.868 Thread-32   TestC.class --- 3
2014-04-08 08:33:20.869 Thread-34   TestC.class --- 5
2014-04-08 08:33:20.869 Thread-37   TestC.class --- 8
2014-04-08 08:33:20.869 Thread-36   TestC.class --- 7
2014-04-08 08:33:20.868 Thread-31   TestC.class --- 2
2014-04-08 08:33:20.869 Thread-38   TestC.class --- 9
2014-04-08 08:33:20.868 Thread-33   TestC.class --- 4
2014-04-08 08:33:20.87  Thread-35   TestC.class --- 6
2014-04-08 08:33:20.925 Thread-39   TestD.class --- 0
2014-04-08 08:33:20.925 Thread-41   TestD.class --- 2
2014-04-08 08:33:20.925 Thread-42   TestD.class --- 3
2014-04-08 08:33:20.926 Thread-43   TestD.class --- 4
2014-04-08 08:33:20.925 Thread-40   TestD.class --- 1
2014-04-08 08:33:20.926 Thread-44   TestD.class --- 5
2014-04-08 08:33:20.926 Thread-46   TestD.class --- 7
2014-04-08 08:33:20.926 Thread-45   TestD.class --- 6
2014-04-08 08:33:20.932 Thread-48   TestD.class --- 9
2014-04-08 08:33:20.932 Thread-47   TestD.class --- 8
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.119 sec
Running TestSuite
2014-04-08 08:33:23.129 Thread-11   TestA.class --- 2
2014-04-08 08:33:23.129 Thread-16   TestA.class --- 7
2014-04-08 08:33:23.129 Thread-14   TestA.class --- 5
2014-04-08 08:33:23.129 Thread-15   TestA.class --- 6
2014-04-08 08:33:23.129 Thread-13   TestA.class --- 4
2014-04-08 08:33:23.129 Thread-18   TestA.class --- 9
2014-04-08 08:33:23.129 Thread-10   TestA.class --- 1
2014-04-08 08:33:23.129 Thread-9    TestA.class --- 0
2014-04-08 08:33:23.129 Thread-12   TestA.class --- 3
2014-04-08 08:33:23.129 Thread-17   TestA.class --- 8
2014-04-08 08:33:23.158 Thread-20   TestB.class --- 1
2014-04-08 08:33:23.158 Thread-19   TestB.class --- 0
2014-04-08 08:33:23.158 Thread-21   TestB.class --- 2
2014-04-08 08:33:23.158 Thread-22   TestB.class --- 3
2014-04-08 08:33:23.158 Thread-23   TestB.class --- 4
2014-04-08 08:33:23.158 Thread-25   TestB.class --- 6
2014-04-08 08:33:23.159 Thread-26   TestB.class --- 7
2014-04-08 08:33:23.159 Thread-24   TestB.class --- 5
2014-04-08 08:33:23.159 Thread-27   TestB.class --- 8
2014-04-08 08:33:23.159 Thread-28   TestB.class --- 9
2014-04-08 08:33:23.171 Thread-29   TestC.class --- 0
2014-04-08 08:33:23.171 Thread-30   TestC.class --- 1
2014-04-08 08:33:23.171 Thread-31   TestC.class --- 2
2014-04-08 08:33:23.171 Thread-32   TestC.class --- 3
2014-04-08 08:33:23.171 Thread-33   TestC.class --- 4
2014-04-08 08:33:23.171 Thread-34   TestC.class --- 5
2014-04-08 08:33:23.172 Thread-35   TestC.class --- 6
2014-04-08 08:33:23.172 Thread-36   TestC.class --- 7
2014-04-08 08:33:23.172 Thread-37   TestC.class --- 8
2014-04-08 08:33:23.172 Thread-38   TestC.class --- 9
2014-04-08 08:33:23.186 Thread-39   TestD.class --- 0
2014-04-08 08:33:23.186 Thread-41   TestD.class --- 2
2014-04-08 08:33:23.186 Thread-42   TestD.class --- 3
2014-04-08 08:33:23.186 Thread-40   TestD.class --- 1
2014-04-08 08:33:23.187 Thread-43   TestD.class --- 4
2014-04-08 08:33:23.187 Thread-46   TestD.class --- 7
2014-04-08 08:33:23.187 Thread-47   TestD.class --- 8
2014-04-08 08:33:23.187 Thread-44   TestD.class --- 5
2014-04-08 08:33:23.187 Thread-45   TestD.class --- 6
2014-04-08 08:33:23.187 Thread-48   TestD.class --- 9
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.23 sec
Running TestSuite
2014-04-08 08:33:25.587 Thread-12   TestA.class --- 3
2014-04-08 08:33:25.587 Thread-17   TestA.class --- 8
2014-04-08 08:33:25.587 Thread-18   TestA.class --- 9
2014-04-08 08:33:25.587 Thread-9    TestA.class --- 0
2014-04-08 08:33:25.587 Thread-11   TestA.class --- 2
2014-04-08 08:33:25.587 Thread-13   TestA.class --- 4
2014-04-08 08:33:25.587 Thread-10   TestA.class --- 1
2014-04-08 08:33:25.587 Thread-15   TestA.class --- 6
2014-04-08 08:33:25.587 Thread-14   TestA.class --- 5
2014-04-08 08:33:25.587 Thread-16   TestA.class --- 7
2014-04-08 08:33:25.62  Thread-20   TestB.class --- 1
2014-04-08 08:33:25.62  Thread-19   TestB.class --- 0
2014-04-08 08:33:25.621 Thread-22   TestB.class --- 3
2014-04-08 08:33:25.621 Thread-23   TestB.class --- 4
2014-04-08 08:33:25.62  Thread-21   TestB.class --- 2
2014-04-08 08:33:25.621 Thread-24   TestB.class --- 5
2014-04-08 08:33:25.621 Thread-26   TestB.class --- 7
2014-04-08 08:33:25.621 Thread-25   TestB.class --- 6
2014-04-08 08:33:25.621 Thread-28   TestB.class --- 9
2014-04-08 08:33:25.621 Thread-27   TestB.class --- 8
2014-04-08 08:33:25.636 Thread-29   TestC.class --- 0
2014-04-08 08:33:25.636 Thread-31   TestC.class --- 2
2014-04-08 08:33:25.636 Thread-30   TestC.class --- 1
2014-04-08 08:33:25.636 Thread-32   TestC.class --- 3
2014-04-08 08:33:25.636 Thread-35   TestC.class --- 6
2014-04-08 08:33:25.636 Thread-33   TestC.class --- 4
2014-04-08 08:33:25.637 Thread-34   TestC.class --- 5
2014-04-08 08:33:25.637 Thread-37   TestC.class --- 8
2014-04-08 08:33:25.637 Thread-36   TestC.class --- 7
2014-04-08 08:33:25.637 Thread-38   TestC.class --- 9
2014-04-08 08:33:25.65  Thread-39   TestD.class --- 0
2014-04-08 08:33:25.65  Thread-41   TestD.class --- 2
2014-04-08 08:33:25.65  Thread-42   TestD.class --- 3
2014-04-08 08:33:25.65  Thread-40   TestD.class --- 1
2014-04-08 08:33:25.65  Thread-43   TestD.class --- 4
2014-04-08 08:33:25.65  Thread-44   TestD.class --- 5
2014-04-08 08:33:25.65  Thread-46   TestD.class --- 7
2014-04-08 08:33:25.651 Thread-48   TestD.class --- 9
2014-04-08 08:33:25.651 Thread-47   TestD.class --- 8
2014-04-08 08:33:25.651 Thread-45   TestD.class --- 6
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.21 sec
Running TestSuite
2014-04-08 08:33:28.079 Thread-13   TestA.class --- 4
2014-04-08 08:33:28.079 Thread-10   TestA.class --- 1
2014-04-08 08:33:28.079 Thread-12   TestA.class --- 3
2014-04-08 08:33:28.079 Thread-17   TestA.class --- 8
2014-04-08 08:33:28.079 Thread-14   TestA.class --- 5
2014-04-08 08:33:28.079 Thread-9    TestA.class --- 0
2014-04-08 08:33:28.079 Thread-11   TestA.class --- 2
2014-04-08 08:33:28.079 Thread-15   TestA.class --- 6
2014-04-08 08:33:28.079 Thread-16   TestA.class --- 7
2014-04-08 08:33:28.079 Thread-18   TestA.class --- 9
2014-04-08 08:33:28.113 Thread-19   TestB.class --- 0
2014-04-08 08:33:28.113 Thread-21   TestB.class --- 2
2014-04-08 08:33:28.113 Thread-20   TestB.class --- 1
2014-04-08 08:33:28.113 Thread-22   TestB.class --- 3
2014-04-08 08:33:28.113 Thread-23   TestB.class --- 4
2014-04-08 08:33:28.114 Thread-27   TestB.class --- 8
2014-04-08 08:33:28.114 Thread-28   TestB.class --- 9
2014-04-08 08:33:28.114 Thread-26   TestB.class --- 7
2014-04-08 08:33:28.114 Thread-25   TestB.class --- 6
2014-04-08 08:33:28.114 Thread-24   TestB.class --- 5
2014-04-08 08:33:28.127 Thread-29   TestC.class --- 0
2014-04-08 08:33:28.127 Thread-31   TestC.class --- 2
2014-04-08 08:33:28.127 Thread-32   TestC.class --- 3
2014-04-08 08:33:28.127 Thread-33   TestC.class --- 4
2014-04-08 08:33:28.127 Thread-30   TestC.class --- 1
2014-04-08 08:33:28.128 Thread-34   TestC.class --- 5
2014-04-08 08:33:28.128 Thread-36   TestC.class --- 7
2014-04-08 08:33:28.128 Thread-35   TestC.class --- 6
2014-04-08 08:33:28.128 Thread-37   TestC.class --- 8
2014-04-08 08:33:28.128 Thread-38   TestC.class --- 9
2014-04-08 08:33:28.14  Thread-40   TestD.class --- 1
2014-04-08 08:33:28.14  Thread-39   TestD.class --- 0
2014-04-08 08:33:28.14  Thread-41   TestD.class --- 2
2014-04-08 08:33:28.14  Thread-42   TestD.class --- 3
2014-04-08 08:33:28.141 Thread-43   TestD.class --- 4
2014-04-08 08:33:28.141 Thread-44   TestD.class --- 5
2014-04-08 08:33:28.141 Thread-45   TestD.class --- 6
2014-04-08 08:33:28.141 Thread-46   TestD.class --- 7
2014-04-08 08:33:28.141 Thread-47   TestD.class --- 8
2014-04-08 08:33:28.146 Thread-48   TestD.class --- 9
Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.271 sec

Results :

Tests run: 160, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.368s
[INFO] Finished at: Tue Apr 08 08:33:30 EDT 2014
[INFO] Final Memory: 7M/121M
[INFO] ------------------------------------------------------------------------

Here is one of the test classes

``` java
package com.company.qed;

import java.sql.Timestamp;

import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

public class TestA 
{
    @Test(dataProvider="data", threadPoolSize=5)
    public void methodA(int i) 
    {
        java.util.Date date= new java.util.Date();
        System.out.println(new Timestamp(date.getTime()) +
                "\tThread-" + Thread.currentThread().getId() + "\tTestA.class --- " + i);
    }

    @DataProvider(name="data", parallel=true)
    public Object[][] data()
    {
        Object[][] fields = new Object[10][1];

        for (int i = 0; i<10; i++) {
            fields[i][0] = i;
        }

        return fields;
    }

}
```

Here is one of the testng xml file

``` xml
<suite name="Suite A">
    <test name="Test Name A">
        <classes>
            <class name="com.company.qed.TestA" />
        </classes>
    </test>
</suite>
```

My solution is to wrap all testng xml file into one testng xml as follows

``` xml
<suite name="TestNG.xml" parallel="instances" thread-count="5">
    <suite-files>
        <suite-file path="./testngA.xml" />
        <suite-file path="./testngB.xml" />
        <suite-file path="./testngC.xml" />
        <suite-file path="./testngD.xml" />
    </suite-files>
</suite>
```

And then reference that in pom.xml. This solution works.

**Comment by jagdeepjain** [comment] 2018-08-04 17:25
any plans to fix this ?

**Comment by krmahadevan** [comment] 2018-08-04 17:26
@jagdeepjain - Is this still a problem with the latest TestNG released version viz., `6.14.3` ? Have you tried ? Can you please help post back your results ?

**Comment by krmahadevan** [comment] 2018-08-04 17:27
Please ensure you try with the latest released version of surefire plugin as well, just to ensure you are able to reproduce this in the latest version.

**Comment by olexmal** [comment] 2019-11-08 13:44
> Please ensure you try with the latest released version of surefire plugin as well, just to ensure you are able to reproduce this in the latest version.

Yes this is happening in TestNg 7.0.0

**Comment by krmahadevan** [comment] 2019-11-08 17:04
@olexmal - Can you please create a simple standalone project that can be used to recreate this issue ?

**Comment by kasivisalakshiBorra** [comment] 2020-03-28 17:05
I am fasing same issue what was the solutions for this issue?

**Comment by krmahadevan** [comment] 2020-03-28 17:18
@kasivisalakshiBorra - My above comment still holds true. Without a reproducible sample, nothing can be said.

**Comment by jagdeepjain** [comment] 2020-08-02 08:59
@krmahadevan apologies for delay in response, to counter this I have used docker container to run it parallel that is running sequential tests in each docker container but spawning few of docker container in parallel.

I have updated the surefire and testNG version as per your recommendation but still it has problem, the test never runs for me with testNG also the test suite has 3 tests but it shows 4 in test run with 1 failure and 3 skipped, may be something else is going on here.

One more thing to highlight that with test suite I am using 
```
  @Test(priority = 1)
  @BeforeTest(groups = "arquillian", inheritGroups = true)
```
In GoogleTest1, GoogleTest2, GoogleTest3.

But when this is removed in GoogleTest4 and run with just ```mvn test -Dtest=GoogleTest4``` this works fine.

Error with testNG test suite is as below when run as ```mvn clean test```

Check below:
```
-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 0.954 s <<< FAILURE! - in TestSuite
org.jagdeep.example.arquillian.google.tests.GoogleTest1.f  Time elapsed: 0.745 s  <<< FAILURE!
java.lang.NullPointerException
	at org.jagdeep.example.arquillian.google.tests.GoogleTest1.f(GoogleTest1.java:21)

```
Above is the console output.

The project is pushed @ https://github.com/jagdeepjain/webdriver-arquillian-test can you please check it once and let know if there is any issue with the project setup or the versions?

**Comment by jagdeepjain** [comment] 2020-08-02 09:10
Let me take back above comment and try after removing arquillian.

**Comment by jagdeepjain** [comment] 2020-08-02 10:37
Ok this works fine for me, code is the branch `parallel-test` in above mentioned repository.

I forcefully made on test failed and below is the console outout.
```
INFO: Detected dialect: W3C
Aug 02, 2020 4:03:33 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
Test Ran fine.
Test Ran fine.
Test Ran from GoogleTest2.
Test Ran from GoogleTest1.
Test Ran fine.
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.734 s <<< FAILURE! - in TestSuite
[ERROR] org.jagdeep.example.arquillian.google.tests.GoogleTest3.f  Time elapsed: 10.356 s  <<< FAILURE!
java.lang.AssertionError: expected [Google] but found [Google1]
	at org.jagdeep.example.arquillian.google.tests.GoogleTest3.f(GoogleTest3.java:23)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   GoogleTest3.f:23 expected [Google] but found [Google1]
[INFO]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[ERROR] There are test failures.

Please refer to /Users/jagdeepjain/git/webdriver-arquillian-test/test-output for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.563 s
[INFO] Finished at: 2020-08-02T16:03:40+05:30
[INFO] Final Memory: 20M/216M
[INFO] ------------------------------------------------------------------------
```

Though the build shows success, I have to look into it.

Thanks @krmahadevan for the tip.

**Comment by jagdeepjain** [comment] 2020-08-02 10:39
@gcosmiano please check with the `parallel-test` branch @ https://github.com/jagdeepjain/webdriver-arquillian-test later I will move this branch in to separate repo for demonstrating the same.

**Comment by krmahadevan** [comment] 2020-08-04 05:04
@jagdeepjain - A bit confused. So are you saying that the issue is not with TestNG but somewhere else ? Or are you saying that the problem persists and needs to be looked at ?

**Comment by jagdeepjain** [comment] 2020-08-04 19:28
@krmahadevan issue shows up when we use TestNG with arquillian as per my findings.

Refer https://github.com/cbeust/testng/issues/508#issuecomment-667647842

**Comment by krmahadevan** [comment] 2023-06-05 13:24
From the above comments, it looks like the problem perhaps could be with arquillian since a plain vanilla project with only TestNG works fine. Closing this issue.

**Closed by krmahadevan** 2023-06-05 13:24 UTC
Labels: Runner: maven, Need: user answer
