### ISSUE TITLE
AfterClass is not running while doing filtering with IMethodInterceptor 

### ISSUE THREAD

**Issue by piwko** [testng-team/testng#462] opened 2013-11-06 09:16 UTC
I have tried to use IMethodInterceptor interceptor for filtering tests in runtime.

In the following example TestNG runs beforeClass, beforeMethod, testMethod1, afterMethod, but afterClass is not running.

TestNG used: 6.8.7

public class TestTypeListener implements IMethodInterceptor {

  @Override
  public List<IMethodInstance> intercept(List<IMethodInstance> methods, ITestContext context) {
    List<IMethodInstance> result = new ArrayList<IMethodInstance>();
    for (IMethodInstance m : methods) {
      Method javaMethod = m.getMethod().getConstructorOrMethod().getMethod();
      Set<String> groups = new HashSet<String>();
      if (javaMethod.isAnnotationPresent(Test.class)) {
        Test test = javaMethod.getAnnotation(Test.class);
        for (String group : test.groups()) {
          groups.add(group);
        }
      }
      if (groups.contains("smoke")) {
        result.add(m);
      }
    }
    return result;
  }
}

public class A {

  @BeforeClass
  public void beforeClass() {
    System.out.println("beforeClass");
  }

  @AfterClass(alwaysRun = true)
  public void afterClass() {
    System.out.println("afterClass");
  }

  @BeforeMethod
  public void beforeMethod() {
    System.out.println("beforeMethod");
  }

  @AfterMethod
  public void afterMethod() {
    System.out.println("afterMethod");
  }

  @Test(groups = { "smoke" })
  public void testMethod1() {
    System.out.println("testMethod1");
  }

  @Test
  public void testMethod2() {
    System.out.println("testMethod2");
  }

}

**Comment by juherr** [comment] 2015-06-30 07:53
Duplicate of #392

**Closed by juherr** 2015-06-30 07:53 UTC
Labels: area: configuration methods, area: listeners
