### ISSUE TITLE
Why is my test case not retried but ignored after execution failure?

### ISSUE THREAD

**Issue by lengmoucool** [testng-team/testng#3087] opened 2024-03-08 11:02 UTC
![微信图片_20240308185709](https://github.com/testng-team/testng/assets/37138978/6628cf24-de4e-4da3-ad67-baaa43367af3)
![微信图片_20240308185715](https://github.com/testng-team/testng/assets/37138978/581573a1-7711-4cb5-affc-a01f98479382)

After adding a retry function to the test cases, I encountered the situation shown in the figure.

What happens when a use case execution fails and is not retried, but is directly ignored?
### TestNG Version
> Note: only the latest version is supported

### Expected behavior
Except the test case could be rerun.

### Actual behavior
Actual the case be ignored.
### Is the issue reproducible on runner?

- [ ] Shell
- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment] 2024-03-08 11:50
Please share a sample that can be used to reproduce the issue and also mention what version of TestNG are you working with.

**Comment by tomzhang-liang** [comment] 2024-03-11 01:43
> Please share a sample that can be used to reproduce the issue and also mention what version of TestNG are you working with.

import com.rationaleemotions.DemoTest.Commentary;
import java.util.concurrent.atomic.AtomicInteger;
import org.testng.Assert;
import org.testng.IExecutionListener;
import org.testng.IRetryAnalyzer;
import org.testng.ITestResult;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

@Listeners(Commentary.class)
public class DemoTest {

  public static final AtomicInteger dataProviderInvocationCount = new AtomicInteger(0);

  @Test(dataProvider = "dp", retryAnalyzer = TryAgain.class)
  public void testMethod(Pojo user) {
    System.out.println("Test is started for data " + user.toString());
    Assert.fail();
  }

  @DataProvider(name = "dp")
  public static Object[][] getTestData() {
    System.err.println(
        "Data Provider invocation count #" + dataProviderInvocationCount.incrementAndGet());
    return new Object[][]{
        {new Pojo().setName("John")}
    };
  }

  public static class TryAgain implements IRetryAnalyzer {

    private int counter = 1;

    @Override
    public boolean retry(ITestResult result) {
      return counter++ != 3;
    }
  }

  public static class Pojo {

    private String name;

    public Pojo() {
      System.err.println("Instantiated " + this);
    }

    public String getName() {
      return name;
    }

    public Pojo setName(String name) {
      this.name = name;
      return this;
    }
  }

  public static class Commentary implements IExecutionListener {

    @Override
    public void onExecutionStart() {}

    @Override
    public void onExecutionFinish() {
      System.err.println(
          "Data Provider was invoked " + dataProviderInvocationCount.get() + " time(s).");
    }
  }
} 
@lengmoucool is my workmate.This is the sample.And the version is  7.9.0.
@krmahadevan

**Comment by krmahadevan** [comment] 2024-03-11 04:17
@lengmoucool @tomzhang-liang - I am not quite sure I understand what the issue is.

From the sample here's what I infer:

* There's a data driven test which is coupled with a retry analyzer
* The retry analyzer is configured to attempt 3 times
* The test method is hard coded to fail all the time.
* TestNG runs the test 3 times and it fails all the times. So it reports the test as `1 failure and 2 skips`.

Can you folks let me know what am I missing here?

Notice the following in the below output:

* The line `Test is started for data com.rationaleemotions.github.issue3087.DemoTest$Pojo@78e117e3` is printed 3 times which signifies that the test was being invoked 3 times.
* The line `Total tests run: 3, Passes: 0, Failures: 1, Skips: 0, Retries: 2` tells you that the test was retried 3 times and it failed. Since there's a retry analyzer involved here, the retried attempts are explicitly mentioned as `retries: 2` and the final failure alone is recorded.

The execution output:

```bash
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Data Provider invocation count #1
Instantiated com.rationaleemotions.github.issue3087.DemoTest$Pojo@78e117e3
Test is started for data com.rationaleemotions.github.issue3087.DemoTest$Pojo@78e117e3

Test ignored.
Test is started for data com.rationaleemotions.github.issue3087.DemoTest$Pojo@78e117e3

Test ignored.
Test is started for data com.rationaleemotions.github.issue3087.DemoTest$Pojo@78e117e3

java.lang.AssertionError: null

	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.fail(Assert.java:116)
	at com.rationaleemotions.github.issue3087.DemoTest.testMethod(DemoTest.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)


===============================================
Default Suite
Total tests run: 3, Passes: 0, Failures: 1, Skips: 0, Retries: 2
===============================================

Disconnected from the target VM, address: '127.0.0.1:50555', transport: 'socket'

Process finished with exit code 0

```

**Comment by tomzhang-liang** [comment] 2024-03-11 08:20
@krmahadevan Yes, Your are right.Thank you for your detailed explanation. I understand now. I made a mistake because I thought that Test ignored means did not execute the test.

**Comment by krmahadevan** [comment] 2024-03-11 08:22
@tomzhang-liang - No problem. Am glad the confusions are cleared. 

Closing this issue

**Closed by krmahadevan** 2024-03-11 08:22 UTC
Labels: Need: user answer
