### ISSUE TITLE
Artifacts deployed to Maven Central don't match git tags

### ISSUE THREAD

**Issue by Stephan202** [testng-team/testng#754] opened 2015-07-15 12:09 UTC
Looking at Maven Central, TestNG up to version [6.9.4](https://repo1.maven.org/maven2/org/testng/testng/6.9.4/testng-6.9.4.pom) has an _optional_ dependency on `junit`. However, the POMs deployed for versions [6.9.5](https://repo1.maven.org/maven2/org/testng/testng/6.9.5/testng-6.9.5.pom) and [6.9.6](https://repo1.maven.org/maven2/org/testng/testng/6.9.6/testng-6.9.6.pom) declare a _compile_ (i.e., unconditional) dependency on `junit`. Confusingly, on Github the [6.9.5 tag](https://github.com/cbeust/testng/blob/testng-6.9.5/pom.xml) and [master](https://github.com/cbeust/testng/blob/master/pom.xml) still list `junit` as an _optional_ dependency.

It seems something in the deployment process alters the POM before uploading?

**Comment by juherr** [comment] 2015-07-15 14:15
Gradle is used now and maven build is deprecated. That could explain the issue. 
I agree we should remove maven files to avoid the confusion.

**Comment by Stephan202** [comment] 2015-07-15 14:21
Assuming Gradle supports this, I'd like to ask that dependencies that were previously marked *optional* are once again marked as such.

**Comment by cbeust** [comment] 2015-07-15 14:25
Definitely, will fix this shortly and I'll get back to you.

-- 
Cédric

**Comment by juherr** [comment] 2015-07-16 07:50
Well, I'm not sure it will be a so easy task: http://stackoverflow.com/questions/25345804/optional-gradle-dependencies-for-maven-libraries

**Comment by krmahadevan** [comment] 2023-06-08 16:12
Closing this issue since we are now completely on Gradle and the published maven artifacts do have the following as optional dependencies 

```xml
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.10.12</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>com.google.inject</groupId>
      <artifactId>guice</artifactId>
      <version>5.1.0</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>2.0</version>
      <optional>true</optional>
    </dependency>
```

**Comment by juherr** [comment] 2023-06-12 08:38
@krmahadevan The issue is still valid because we are not applying a tag during the release process which is a good practice.

**Comment by krmahadevan** [comment] 2023-06-12 08:40
@juherr - i didn't quite understand what do you mean by 

>  we are not applying a tag during the release process which is a good practice.

The release plugin that we use, does automatically create the tags (when we publish to maven (as release candidate) and when we release to maven as a released artifact based on a release candidate). I am not manually creating those tags.
Is that not sufficient, or am I missing something. Please clarify

**Comment by krmahadevan** [comment] 2023-06-12 08:44
Here's the output of the latest tags

```bash
git for-each-ref --format '%(refname) %09 %(taggerdate) %(subject) %(taggeremail)' refs/tags  --sort=taggerdate
```

```bash
refs/tags/7.8.0-rc1      Sun May 7 09:26:45 2023 +0000  <runner@fv-az178-99.ou4bps3zwvpehennzi3rrspmbh.dx.internal.cloudapp.net>
refs/tags/7.8.0-rc2      Thu May 18 19:56:54 2023 +0000  <runner@fv-az555-206.gdyy5qod0nmupdgvnjuye0vnaa.cx.internal.cloudapp.net>
refs/tags/7.8.0          Fri May 19 05:37:24 2023 +0000  <runner@fv-az306-773.jmregfajfmhelj5hmjabl4nu2g.cx.internal.cloudapp.net>
```

referred from. https://stackoverflow.com/a/63395366/679824

**Comment by juherr** [comment] 2023-06-12 09:56
Sorry, you're right. Don't know why I didn't see it at the first look.

**Closed by juherr** 2023-06-12 09:56 UTC
Labels: site/doc

**Comment by krmahadevan** [comment] 2023-06-12 11:00
NO worries. For a second I thought I was missing something that is still pending :) Thanks for confirming that this is done. Trying to clear our issues backlog.
