### ISSUE TITLE
group-by-instances with test dependencies causes instantiation of tests to exponentially slow

### ISSUE THREAD

**Issue by mfulton26** [testng-team/testng#1081] opened 2016-07-01 19:05 UTC
I recently ran into an issue where TestNG is taking a really long time graphing the order to run tests in. If I don't use `dependsOnMethods` then by 1600 test instances (3200 test methods plus some before/after methods) start to run after a second or so but once I add a single `dependsOnMethods` declaration my tests take over 5 minutes to get ordered and that's even before anything is run.

| # instances | total duration (s) |
| --- | --- |
| 100 | 0.4504 |
| 200 | 1.449 |
| 300 | 2.740 |
| 400 | 5.498 |
| 500 | 10.28 |
| 600 | 17.82 |
| 700 | 28.59 |
| 800 | 45.10 |
| 900 | 59.39 |
| 1000 | 81.54 |
| 1100 | 109.56 |
| ... | ... |
| 1600 | 364.92 |

As you can tell, the growth rate is exponential. Is there any way to speed up this process?

Here is some test code which demonstrates the issue:

``` kotlin
import com.google.common.base.Stopwatch
import org.testng.annotations.*

data class TestInstance(val id: Int) {
    companion object {
        init {
            val stopwatch = Stopwatch.createStarted()
            Runtime.getRuntime().addShutdownHook(Thread(Runnable { println(stopwatch) }))
        }

        @Factory fun instances(): Array<Any> = Array(1600) { id -> TestInstance(id) }
    }

    @BeforeMethod fun beforeMethod() = Unit
    @Test fun something() = Unit
    @Test(dependsOnMethods = arrayOf("something")) fun somethingElse() = Unit
    @AfterMethod fun afterMethod() = Unit
    @AfterSuite fun afterSuite() = Unit
}
```

**Comment by cbeust** [comment] 2016-07-01 22:18
Looks like you've found a weakness in the topological sorting of methods.
Thanks for the simple reproducible test case.

@juherr, think you could look into it?


-- 
Cédric

**Comment by juherr** [comment] 2016-07-02 07:34
@cbeust For sure, but not sure I will be available in next weeks.

**Comment by juherr** [comment] 2016-07-02 23:14
Looks similar to #1077

**Comment by juherr** [comment] 2016-07-03 08:50
After 2min of the test run:

![2016-07-03](https://cloud.githubusercontent.com/assets/254697/16544549/58632f22-410b-11e6-9d69-e3310f0c3baa.png)

I think something should be rework with Graph:
![2016-07-03 1](https://cloud.githubusercontent.com/assets/254697/16544570/cde661ec-410b-11e6-83f6-36de24050553.png)

@cbeust What about a dedicated library as you already use more/less the same object(s) with kobalt?
Or maybe replace it by https://github.com/jgrapht/jgrapht ?

**Comment by cbeust** [comment] 2016-07-03 13:09
It's a possibility but all I need is topological sorting, which is really just twenty lines at most. I'd really like to understand what's wrong with the current code before doing that.

**Comment by cbeust** [comment] 2016-07-03 14:43
I looked into that, so far, it looks like both the initialization and `MethodHelper#topologicalSort` are the ones taking a long time.

@juherr Feel free to experiment with `jgrapht` for topological sorting if you want.

**Comment by juherr** [comment] 2016-07-03 16:50
It looks `MethodHelper#topologicalSort` is taking time because `BaseTestMethod#equals` is taking time. I didn't find a way to optimise it. Maybe we should find a way to limit number of calls.

I will try `jgrapht` to see if it could help or not.

**Comment by cbeust** [comment] 2016-07-05 15:23
If `equals` is the reason for the slowdown, as @juherr pointed out on the other issue, then switching to a different algorithm for topological sorting won't make much difference.

But I suspect what's happening is multiple things at the same time so worth investigating.

**Comment by juherr** [comment] 2016-07-06 07:30
I don't know if the problem is `equals` itself but it is what JProfiler showed me. Maybe, the problem is more the number of calls of the method.

**Comment by Aheiss** [comment] 2018-02-19 15:08
Hey Guys,

  I have been looking into this issue since it is causing problems with being able to run our full test suite. I found a fix that improves performance significantly when running a suite that contains a large number of classes. When trying to run our full suite which consists of about 700 classes containing a total of 8500 test methods on version 6.14.2 the suite never loads similar to what is described in [#1077](https://github.com/cbeust/testng/issues/1077). As pointed out above the issue appears to be be in MethodHelper#topologicalSort looking even further down it looks like MethodHelper#matchmethod gets bogged down when trying to match a regex when a large array is passed, this is true especially when the matching method is far down in the array. I was able to get around this issue by modifying MethodHelper#topologicalSort to first splitting all the methods into their associated class then adding an additional for loop to iterate through all the classes then using the existing for loop to iterates through all the methods in the class to find the dependeduponmethod.

             //Create Map of classes that contain test methods
		LinkedHashMap<ITestClass, ArrayList<ITestNGMethod>> classMethods =  sortIntoClasses(methods);	
		//
		// Create the graph
		//
		for (Map.Entry<ITestClass, ArrayList<ITestNGMethod>> testClass : classMethods.entrySet()) {
			
			//Changed to sort methods in class instead of all methods
			// for (ITestNGMethod m : methods) {
			
			for (ITestNGMethod m : testClass.getValue()) {
				ITestNGMethod[] testList = testClass.getValue().toArray(new ITestNGMethod[testClass.getValue().size()]);
				
				result.addNode(m);

				List<ITestNGMethod> predecessors = Lists.newArrayList();

				String[] methodsDependedUpon = m.getMethodsDependedUpon();
				String[] groupsDependedUpon = m.getGroupsDependedUpon();

				if (methodsDependedUpon.length > 0) {
					ITestNGMethod[] methodsNamed = MethodHelper.findDependedUponMethods(m, testList);
					for (ITestNGMethod pred : methodsNamed) {
						predecessors.add(pred);
					}
				}

I would like to note that this does **NOT** fix the performance when creating tests using a @factory. This only improves performance when test are grouped by classes. I am just starting to look into the factory issue and will add any new information if I find it.

Here is the sortIntoClasses method is being used above :

    private static LinkedHashMap<ITestClass, ArrayList<ITestNGMethod>> sortIntoClasses(ITestNGMethod[] methods) {
		LinkedHashMap<ITestClass, ArrayList<ITestNGMethod>> result = new LinkedHashMap<>();
		for (ITestNGMethod method : methods) {
			// Extract key
			ITestClass methodClass = method.getTestClass();
			// Class already in map
			if (result.containsKey(methodClass)) {
				ArrayList<ITestNGMethod> methodList = result.get(methodClass);
				methodList.add(method);
				result.put(methodClass, methodList);
			} else {
				ArrayList<ITestNGMethod> methodList = new ArrayList<>();
				methodList.add(method);
				result.put(methodClass, methodList);
			}
		}
		return result;

	}

**Comment by juherr** [comment] 2018-02-19 15:13
@Aheiss I can't wait your pull request! 👍

**Comment by Aheiss** [comment] 2018-02-20 16:01
I found a way to fix the performance issue with factories as well by grouping all the methods by their instance.
The performance issue seems to revolve around scope. The current findDepenedUponMethods returns ALL methods that have a dependsUpon even if they are not from the same instance. 

Is it safe to assume that a @test must be in the same instance in order to depend upon another @test?

**Comment by juherr** [comment] 2018-02-20 16:11
If the tests are all passed then yes, we can assume it.

WDYT @krmahadevan @selenareneephillips

**Comment by krmahadevan** [comment] 2018-02-20 16:13
@Aheiss - yes w.r.t. factories that should be a safe assumption

**Comment by krmahadevan** [comment] 2018-02-23 08:49
Closing this issue since its been fixed via PR https://github.com/cbeust/testng/pull/1705

**Closed by krmahadevan** 2018-02-23 08:49 UTC
Labels: area: method dependencies, area: execution order, type: enhancement, aspect: performance
