### ISSUE TITLE
parameter on suite level not acknowledged in testng-failed

### ISSUE THREAD

**Issue by hnestorova** [testng-team/testng#1887] opened 2018-08-07 14:45 UTC
### TestNG Version
TestNG version 6.11.0

### Expected behavior
serverUrl on suite level will be added to the `testng-failed.xml` for all failed cases from testClass1
serverUrl on test level will be added to the `testng-failed.xml` for all failed cases from testClass2

### Actual behavior
serverUrl on test level is added to the `testng-failed.xml` for all failed cases from testClass1 and testClass2

### Test case sample
```xml
<suite name="Name" parallel="classes" thread-count="5">
    <parameter name="serverUrl" value="http://PRIVATE:8080/PRIVATE"/>
    <test verbose="1" name="Name 1" annotations="JDK">
        <parameter name="userName" value="user1"/>
        <parameter name="password" value="pass1"/>
        <classes>
            <class name="testClass1"/>
        </classes>
    </test>
    <test verbose="1" name="Name 2" annotations="JDK">
        <parameter name="serverUrl" value="http://PRIVATE/PRIVATE"/>
        <parameter name="userName" value="user2"/>
        <parameter name="password" value="pass2"/>
        <classes>
            <class name="testClass2"/>
        </classes>
    </test>
</suite>
```

**Comment by krmahadevan** [comment] 2018-08-08 04:35
@hnestorova - Can you please retry using the latest released version of TestNG `6.14.3` as of today.
If the problem still exists, please help share a sample that can be used to reproduce the issue easily.

**Comment by hnestorova** [comment] 2018-08-14 09:37
@krmahadevan , same problem with the newest testng version. I have provided an xml example in the issue description, let me know what other info you need

**Comment by krmahadevan** [comment] 2019-03-12 03:22
Attempted at reproducing this issue using TestNG `7.0.0-beta3`. Unable to reproduce this issue.

Here's how my test classes look like

```java
package com.rationaleemotions.github.issue1887;

import org.testng.Reporter;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class SampleTestClassOne {
  @Test
  @Parameters({"serverUrl", "userName", "password"})
  public void testMethod(String serverUrl, String userName, String password) {
    String testClassName = getClass().getCanonicalName();
    String testName = Reporter.getCurrentTestResult().getTestContext().getName();
    String suiteName = Reporter.getCurrentTestResult().getTestContext().getSuite().getName();
    System.err.println(String.format("[Suite]<%s>.[Test]<%s>.%s", suiteName, testName, testClassName));
    System.err.println("Server Url :" + serverUrl);
    System.err.println("Username :" + userName);
    System.err.println("Password :" + password);
  }
}
```

```java
package com.rationaleemotions.github.issue1887;

import org.testng.Reporter;
import org.testng.annotations.Parameters;
import org.testng.annotations.Test;

public class SampleTestClassTwo {
  @Test
  @Parameters({"serverUrl", "userName", "password"})
  public void testMethod(String serverUrl, String userName, String password) {
    String testClassName = getClass().getCanonicalName();
    String testName = Reporter.getCurrentTestResult().getTestContext().getName();
    String suiteName = Reporter.getCurrentTestResult().getTestContext().getSuite().getName();
    System.err.println(String.format("[Suite]<%s>.[Test]<%s>.%s", suiteName, testName, testClassName));
    System.err.println("Server Url :" + serverUrl);
    System.err.println("Username :" + userName);
    System.err.println("Password :" + password);
    throw new RuntimeException("Simulating a failure");
  }
}
```

Here's how my suite xml looks like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="200_suite" verbose="2">
  <parameter name="serverUrl" value="http://PRIVATE:8080/PRIVATE"/>
  <test verbose="1" name="Name 1" annotations="JDK">
    <parameter name="userName" value="user1"/>
    <parameter name="password" value="pass1"/>
    <classes>
      <class name="com.rationaleemotions.github.issue1887.SampleTestClassOne"/>
    </classes>
  </test>
  <test verbose="1" name="Name 2" annotations="JDK">
    <parameter name="serverUrl" value="http://PRIVATE/PRIVATE"/>
    <parameter name="userName" value="user2"/>
    <parameter name="password" value="pass2"/>
    <classes>
      <class name="com.rationaleemotions.github.issue1887.SampleTestClassTwo"/>
    </classes>
  </test>
</suite>
```

Here's the execution output

```bash
...
... TestNG 7.0.0-beta3 by Cédric Beust (cedric@beust.com)
...
[Suite]<200_suite>.[Test]<Name 1>.com.rationaleemotions.github.issue1887.SampleTestClassOne
Server Url :http://PRIVATE:8080/PRIVATE
Username :user1
Password :pass1
PASSED: testMethod("http://PRIVATE:8080/PRIVATE", "user1", "pass1")

===============================================
    Name 1
    Tests run: 1, Failures: 0, Skips: 0
===============================================
[Suite]<200_suite>.[Test]<Name 2>.com.rationaleemotions.github.issue1887.SampleTestClassTwo
Server Url :http://PRIVATE/PRIVATE
Username :user2
Password :pass2

java.lang.RuntimeException: Simulating a failure

	at com.rationaleemotions.github.issue1887.SampleTestClassTwo.testMethod(SampleTestClassTwo.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

FAILED: testMethod("http://PRIVATE/PRIVATE", "user2", "pass2")
java.lang.RuntimeException: Simulating a failure
	at com.rationaleemotions.github.issue1887.SampleTestClassTwo.testMethod(SampleTestClassTwo.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner.privateRun(TestRunner.java:763)
	at org.testng.TestRunner.run(TestRunner.java:594)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
	at org.testng.SuiteRunner.run(SuiteRunner.java:304)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
	at org.testng.TestNG.runSuites(TestNG.java:997)
	at org.testng.TestNG.run(TestNG.java:965)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)


===============================================
    Name 2
    Tests run: 1, Failures: 1, Skips: 0
===============================================

===============================================
200_suite
Total tests run: 2, Passes: 1, Failures: 1, Skips: 0
===============================================


Process finished with exit code 0
```

Here's how the `testng-failed.xml` file looks like

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite guice-stage="DEVELOPMENT" verbose="2" name="Failed suite [200_suite]">
  <parameter name="serverUrl" value="http://PRIVATE:8080/PRIVATE"/>
  <test thread-count="5" verbose="2" name="Name 2(failed)">
    <parameter name="password" value="pass2"/>
    <parameter name="serverUrl" value="http://PRIVATE/PRIVATE"/>
    <parameter name="userName" value="user2"/>
    <classes>
      <class name="com.rationaleemotions.github.issue1887.SampleTestClassTwo">
        <methods>
          <include name="testMethod" invocation-numbers="0"/>
        </methods>
      </class> <!-- com.rationaleemotions.github.issue1887.SampleTestClassTwo -->
    </classes>
  </test> <!-- Name 2(failed) -->
</suite> <!-- Failed suite [200_suite] -->
```

Closing this issue. If this issue still persists pls help add a full fledged sample that can be used to reproduce the problem using `7.0.0-beta3`

**Closed by krmahadevan** 2019-03-12 03:22 UTC
Labels: area: reporting, area: xml suites
