### ISSUE TITLE
Allow multiple IMethodInterceptors

### ISSUE THREAD

**Issue by jharting** [testng-team/testng#601] opened 2015-02-05 09:52 UTC
There seems to be a limitation that only the last IMethodInterceptor listed in the xml file will be used. It would be more useful if several independent interceptors could be registered, cooperating via a shared context if needed.

**Comment by juherr** [comment] 2015-04-23 08:24
#625 seems to fix what you ask

**Comment by jharting** [comment] 2015-04-23 09:55
Yes exactly. Hopefully it gets merged soon!

**Comment by juherr** [comment] 2015-04-28 08:14
Duplicate of #625

**Closed by juherr** 2015-04-28 08:14 UTC
Labels: area: listeners
