### ISSUE TITLE
While creating a custom code for html table in emailablereport.html, Multiple <br> tags are getting added 

### ISSUE THREAD

**Issue by jayshreekant** [testng-team/testng#3144] opened 2024-06-25 09:39 UTC
### TestNG Version
> Note: only the latest version is supported
7.10.2

### Expected behavior
Should not add <br> tag, until explicitly mentioned in the Reporter Log

### Actual behavior
While creating a custom code for table in emailablereport, Multiple <br> tags are getting added 

### Is the issue reproducible on runner?

- [ ] Shell
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse
- [ ] IntelliJ
- [ ] NetBeans

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

![image](https://github.com/testng-team/testng/assets/12380291/d7cf01e7-971a-4738-81d1-81076f2b389d)

![image](https://github.com/testng-team/testng/assets/12380291/a1c5e8f0-57fa-4eaf-9efe-118f960f8398)

![image](https://github.com/testng-team/testng/assets/12380291/410eaa4e-fa79-4064-97b8-170a550dd950)

### Contribution guidelines

Incase you plan to raise a pull request to fix this issue, please make sure you refer our [Contributing](.github/CONTRIBUTING.md) section for detailed set of steps.

**Comment by krmahadevan** [comment] 2024-06-25 09:44
@jayshreekant - It's not clear what the issue is. Can you please help share a sample project that can be used to reproduce the problem? If the issue is with the default TestNG reporters that come bundled with TestNG, then maybe you could mention the report name and/or the listener class from wherein you think this discrepancy is popping up.

**Comment by jayshreekant** [comment] 2024-06-27 13:08
Kindly execute this code using **mvn clean test**

[DemoMavenProject.zip](https://github.com/user-attachments/files/16014471/DemoMavenProject.zip)

and Iterate to \DemoMavenProject\target\surefire-reports\emailable-report.html

and check how many <br> tag has been added in the table.


![image](https://github.com/testng-team/testng/assets/12380291/c5619abe-86b6-4b6e-aebb-537c0004b1c0)

**Comment by krmahadevan** [comment] 2024-06-27 13:51
@jayshreekant - The problem lies in your test code. You are basically trying to construct a html table using a series of `Reporter.log()` messages. I believe this is what skews up the entire html report.

The Emailable HTML Report was never meant for such sophisticated usecases I believe. You should ideally speaking be building your own reporting solutions.

All said and done, the below altered sample test code will ensure that the problem goes away. The code that I am sharing below basically constructs the entire html table as a single string and dumps it as 1 log message (instead of doing it as n log messages which your sample was doing)

```java
import org.testng.Reporter;
import org.testng.annotations.Test;

public class ErrorLotOfBreak {
    @Test
    public void ErrorLotofBreak() {

        Reporter.log("Sample Text 1");
        Reporter.log("Sample Text 2");
        Reporter.log("Sample Text 3");
        Reporter.log("Sample Text 4");
        Reporter.log("Sample Text 5");
        Reporter.log(buildTable());
    }

    private static String buildTable() {
        return "<table><th>Age/Priority</th><th>URL</th><th>Count ()</th><th>Status</th>" +
                "<tr>" +
                "<td>" + "Ram" + "</td>" +
                "<td>" + "Shyam" + "</td>" +
                "<td>" + "Dheeraj" + "</td>" +
                "<td>" + " Alert " + "</td>" +
                "</tr>" +
                "<tr>" +
                "<td>" + "Ram" + "</td>" +
                "<td>" + "Shyam" + "</td>" +
                "<td>" + "Dheeraj" + "</td>" +
                "<td>" + " Alert " + "</td>" +
                "</tr>" +
                "<tr>" +
                "<td>" + "Ram" + "</td>" +
                "<td>" + "Shyam" + "</td>" +
                "<td>" + "Dheeraj" + "</td>" +
                "<td>" + " Alert " + "</td>" +
                "</tr>" +
                "<tr>" +
                "<td>" + "Ram" + "</td>" +
                "<td>" + "Shyam" + "</td>" +
                "<td>" + "Dheeraj" + "</td>" +
                "<td>" + " Alert " + "</td>" +
                "</tr>" +
                "<tr>" +
                "<td>" + "Ram" + "</td>" +
                "<td>" + "Shyam" + "</td>" +
                "<td>" + "Dheeraj" + "</td>" +
                "<td>" + " Alert " + "</td>" +
                "</tr>" +
                "</table>";
    }
}
```

<img width="836" alt="image" src="https://github.com/testng-team/testng/assets/909773/becd9f25-a396-44fa-8c15-40d1cc7ef8b5">


Am closing this issue as **question answered**, since there's not much that can be done from TestNG side in this case.

**Closed by krmahadevan** 2024-06-27 13:51 UTC
Labels: needs-sample
